options:
  # Global options
  server:
    description: >-
      Required if not related to the vSphere Integrator. vSphere ip address
      e.g. `128.110.154.166`
    type: string

  username:
    description: >-
      Required if not related to the vSphere Integrator. vSphere username
    type: string

  password:
    description: >-
      Required if not related to the vSphere Integrator. vSphere password
    type: string

  datacenter:
    description: >-
      Required if not related to the vSphere Integrator. vSphere datacenter
    type: string

  control-node-selector:
    description: |
      Specifies to which nodes this operator adds the vsphere-cpi daemonsets
      Declare node labels in key=value format, separated by spaces.
      It's also valid to not have a value, this is interpretted as an empty string.

      Required if not related to kubernetes-control-plane:kube-control

      e.g. 
        node-role.kubernetes.io/control-plane=custom-value
        node-role.kubernetes.io/control-plane=
    type: string

  image-registry:
    type: string
    description: |
      Source registry of metrics server images.

      By setting to a value, each image listed in the releases manifest
      has its image-registry replaced.

      If unset, the manifests will use the image registry from the kube-control relation

      example)
        juju config kubernetes-metrics-server image-registry='rocks.canonical.com:443/cdk'

        juju config kubernetes-metrics-server --reset image-registry

  provider-release:
    type: string
    description: |
      Specify the version of cloud-provider as defined by the `releases`
      directory of https://github.com/kubernetes/cloud-provider-vsphere/

      example)
        juju config vsphere-cloud-provider provider-release='v1.22'
      
      A list of supported versions is available through the action:
        juju run-action vsphere-cloud-provider/0 list-releases --wait
      
      To reset by to the latest supported by the charm use:
        juju config vsphere-cloud-provider --reset provider-release
      
      The current release deployed is available by viewing
        juju status vsphere-cloud-provider

  storage-release:
    type: string
    description: |
      Specify the version of storage-provider as defined by the `release`
      tags of https://github.com/kubernetes-sigs/vsphere-csi-driver

      example)
        juju config vsphere-cloud-provider storage-release='v2.5.1'
      
      A list of supported versions is available through the action:
        juju run-action vsphere-cloud-provider/0 list-releases --wait
      
      To reset by to the latest supported by the charm use:
        juju config vsphere-cloud-provider --reset storage-release
      
      The current release deployed is available by viewing
        juju status vsphere-cloud-provider